#pragma once
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <string>
#include <string.h>
#include <vector>
#include <ostream>
#include "Common.h"
#include "Time.h"
#include "Room.h"
#include "course.h"